server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

path:

twitter:
  key: TynCi8QMLZTYoYDSoa8rY4wuP
  secret: IWi2VWzLARIumoG5gWyUjsLjyp2llVADaKafwo3iiuxOGhIlRj

---

spring:
  profiles:
    active: local

---

spring:
  profiles:
    active: prd

---

spring:
  profiles:
    active: @spring.profiles.active@