server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

path:

twitter:
  key: TynCi8QMLZTYoYDSoa8rY4wuP
  secret: IWi2VWzLARIumoG5gWyUjsLjyp2llVADaKafwo3iiuxOGhIlRj

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      static-path-pattern: /resources/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://greenworld.dscloud.me:3306/blog
    username: root
    password: P!ssw0rd

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB